project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path
from projectapp import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$',views.index, name='index'),
    url(r'gejala/',include('projectapp.urls')),
    url(r'external/',views.external),
    url(r'generate_table/',views.generate_table,name='generate_table'),
]

projectapp/urls.py
from django.conf.urls import url
from projectapp import views

# TEMPLATE TAGGING
app_name = 'projectapp'

urlpatterns=[
    url(r'^index/$',views.index,name='index'),
    url(r'^gejala/$',views.gejala,name='gejala'),
    url(r'^daftarrsrujukan/$',views.daftarrsrujukan,name='daftarrsrujukan'),
    url(r'^coba/$',views.coba,name='coba'),
    url(r'^external/$',views.external),
]

projectapp/models.py
from django.db import models

# Create your models here.

projectapp/views.py
from django.shortcuts import render
import requests
import sys
from subprocess import run,PIPE
from django.http import HttpResponse



# Create your views here.
def index(request):
    return render(request,'projectapp/index.html')

def gejala(request):
    return render(request,'projectapp/gejala.html')

def daftarrsrujukan(request):
    return render(request,'projectapp/daftarrsrujukan.html')

def coba(request):
    return render(request,'projectapp/coba.html')

def external(request):
    inp = request.POST.get('param')
    out = run([sys.executable,'C:/Users/GANESHA/Desktop/project/test.py',inp],shell=False,stdout=PIPE)
    text=str(out.stdout)
    text=text[2:]
    text=text[:-5]

    return render(request,'projectapp/coba.html',{'data1':text})

def generate_table(request):

    #Dapatkan input yang dikirim
    import json
    post = json.loads(request.POST.get('data',''))

    input_name=post['input_name']
    input_salary=int(post['input_salary'])
    input_multiplier=int(post['input_multiplier'])

    #Jalankan script python mu di sini, sebagai contoh aku bikin script utk buat table aja
    import pandas as pd
    df=pd.DataFrame({"Name":[input_name],
                     "Salary":[input_salary],
                     "Total Salary":[input_salary*input_multiplier]
                    })

    #Untuk mengirim dataframe balik, harus di konversi menjadi json:
    def ser_df(df):
        df_columns= [{"data":f,"field": f, "title": f} for f in df]
        df_data = df.to_dict('records')
        ser_data={'data': df_data,'columns': df_columns}
        return ser_data

    table=ser_df(df)

    context={'table':table}
    context=json.dumps(context)

    #Kirim balik isi 'context' ke html. Ini akan masuk ke variable 'response' nya
    return HttpResponse(context, content_type="application/json")

templates/projectapp/coba.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!--IMPORT JQUERY-->
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>

    <!--IMPORT DATATABLES-->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>

    <meta charset="utf-8">
    <title>Coba</title>
  </head>

  <body>
    <h1>Coba Berhasil</h1>

    <!-- Bikin Form -->

    Name:
    <input type="text" id="input_name" value="Bob">
    <br>

    Salary:
    <input type="number" id="input_salary" value=1000>
    <br>

    Multiplier:
    <input type="number" id="input_multiplier" value=5>
    <br><br>

    <!-- Bikin Button. Waktu di click dia jalanin fungsi Generate() -->
    <button onclick="Generate()"> Create Table </button>

    <br><br>

    <!-- Tabel nanti muncul di sini -->
    <table id="my_table" class="display">
    </table>

  </body>

</html>

<script>

  function Generate(){

    //Dapatkan nilai dari input form berdasarkan id mereka
    var input_name=$("#input_name").val()
    var input_salary=$("#input_salary").val()
    var input_multiplier=$("#input_multiplier").val()

    //Masukan jadi satu paket yang akan di kirim
    var post={'input_name':input_name,
              'input_salary':input_salary,
              'input_multiplier':input_multiplier}

    //Jalankan ajax
    //ajax akan menjalankan python script dalam url nya (def generate_table)
    $.ajax({
      type: "POST",
      url: "{% url 'generate_table'%}",
      data: {csrfmiddlewaretoken: '{{ csrf_token }}','data':JSON.stringify(post)},
      success: function callback(response){
           //Jika berhasil, hasil script akan di kembalikan dalam variable response
           console.log(response);
           //Buat table dengan hasil response
           LoadTable(response)
        }
    });

  }

  //Fungsi pembuat datatable
  function LoadTable(response){

    $('#my_table').dataTable({
      destroy: true,
      data: response['table']['data'],
      columns: response['table']['columns'],
    });

  }

</script>

templates/projectapp/daftarrsrujukan.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Daftar Rs Rujukan</title>
  </head>
  <body>
    <h1>Daftar RS Rujukan</h1>
  </body>
</html>

templates/projectapp/dua.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Berhasil</title>
  </head>
  <body>
    <h1>Ini halaman ke dua</h1>

    <div class="container">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Email</th>
            <th>DayStarted</th>
            <th>Location</th>
          </tr>
        </thead>
        <tbody>
          {% for Employee in istekler %}
          <tr>
            <td>{{ Employee.first_name }}</td>
            <td>{{ Employee.last_name }}</td>
            <td>{{ Employee.email }}</td>
            <td>{{ Employee.day_started }}</td>
            <td>{{ Employee.location }}</td>
          </tr>
          {% endfor %}
    </tbody>
  </table>
</div>

  </body>
</html>

templates/projectapp/format.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Form</title>
  </head>
  <body>
    <h1>Form</h1>
    <form method='post'>
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit"> Submit</button>
    </form>

  </body>
</html>

templates/projectapp/gejala.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <title>Training Studio - Free CSS Template</title>
    <style>h1{
            color:red;
            font-size:20px;
    }

    h2{
      text-align: center;
    }

        </style>

<!--

TemplateMo 548 Training Studio

https://templatemo.com/tm-548-training-studio

-->
    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css"%}">

    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.css"%}">

    <link rel="stylesheet" href="{% static "css/templatemo-training-studio.css"%}">

    </head>

    <body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
      <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </div>
    <!-- ***** Preloader End ***** -->


    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">Covid<em> -19</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{% url 'projectapp:index' %}" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="{% url 'projectapp:index' %}">Sebaran Covid-19</a></li>
                            <li class="scroll-to-section"><a href="{% url 'projectapp:daftarrsrujukan'%}">Daftar RS Rujukan</a></li>
                            <li class="scroll-to-section"><a href="#trainers">Berita</a></li>
                            <form class="form-inline d-flex justify-content-center md-form form-sm active-pink-2 mt-2">
                              <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
                            </form>
                            <li class="main-button"><a href="{% url 'projectapp:coba'%}">Coba</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

<!-- ***** Main Banner Area Start ***** -->
    <div class="main-banner" id="top">
        <video autoplay muted loop id="bg-video">
            <source src="{% static "images/caracegahpenularanviruscorona.mp4" %}" type="video/mp4" />
        </video>

        <div class="video-overlay header-text">
            <div class="caption">
                <h2>Form <em>Gejala</em></h2>
                <div class="main-button scroll-to-section">
                    <a href="#form">Isi Disini</a>
                </div>
            </div>
        </div>
    </div>
<!-- ***** Main Banner Area End ***** -->

<!-- Form -->
<br><br>
<h2 id="form">Merasakan gejala Covid-19 ? Isi pertanyaan di bawah untuk tau tindakan lebih lanjut</h2>
<div class="container">
<form method="post">
  <div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" class="form-control" id="nama" placeholder="Nama Lengkap">
  </div>
  <div class="form-group">
    <label for="nama">Usia</label>
    <input type="text" class="form-control" id="nama" placeholder="Usia Saat Ini">
  </div>
  <div class="form-group">
    <label class="my-1 mr-2" for="jeniskelamin">Jenis Kelamin</label>
    <select class="custom-select my-1 mr-sm-2" id="jeniskelamin">
      <option selected>Choose...</option>
      <option value="1">Laki-Laki</option>
      <option value="2">Perempuan</option>
    </select>
  </div>
  <div class="form-group">
    <label class="my-1 mr-2" for="kontak">Pernah kontak dengan pasien positif COVID-19 ? (Berada dalam 1 ruangan yang sama/kontak dalam jarak 1 meter) ATAU pernah berkunjungke negara/daerah endemis COVID-19 dalam 14 hari terakhir ?</label>
    <select class="custom-select my-1 mr-sm-2" id="kontak">
      <option selected>Choose...</option>
      <option value="1">Ya</option>
      <option value="2">Tidak</option>
    </select>
  </div>
  <div class="form-group">
    <label class="my-1 mr-2" for="gejala">Sedang atau pernah mengalami: - Demam (>38 C) - Pilek - Batuk - Sesak Napas</label>
    <select class="custom-select my-1 mr-sm-2" id="gejala">
      <option selected>Choose...</option>
      <option value="1">Ya</option>
      <option value="2">Tidak</option>
    </select>
  </div>
  <div class="form-group">
    <label class="my-1 mr-2" for="setelahkarantinamandiri">Setelah 14 hari karantina diri, Anda mengalami: - Demam (>38 C) - Pilek - Batuk - Sesak Napas</label>
    <select class="custom-select my-1 mr-sm-2" id="setelahkarantinamandiri">
      <option selected>Choose...</option>
      <option value="1">Ya</option>
      <option value="2">Tidak</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>


<!-- Button trigger modal -->
<br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" id="hasil">
  Lihat Hasilnya
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Berhasil</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2020 Training Studio

                    - Designed by <a rel="nofollow" href="https://templatemo.com" class="tm-text-link" target="_parent">TemplateMo</a></p>

                    <!-- You shall support us a little via PayPal to info@templatemo.com -->

                </div>
            </div>
        </div>
    </footer>



    <!-- jQuery -->
    <script src="{% static "js/jquery-2.1.0.min.js" %}"></script>

    <!-- Bootstrap -->
    <script src="{% static "js/popper.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Plugins -->
    <script src="{% static "js/scrollreveal.min.js" %}"></script>
    <script src="{% static "js/waypoints.min.js" %}"></script>
    <script src="{% static "js/jquery.counterup.min.js" %}"></script>
    <script src="{% static "js/imgfix.min.js" %}"></script>
    <script src="{% static "js/mixitup.js" %}"></script>
    <script src="{% static "js/accordions.js" %}"></script>

    <!-- Global Init -->
    <script src="{% static "js/custom.js" %}"></script>

  </body>
</html>

templates/projectapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

    <title>Training Studio - Free CSS Template</title>
    <style>h1{
            color:red;
            font-size:20px;
    }
        </style>

<!--

TemplateMo 548 Training Studio

https://templatemo.com/tm-548-training-studio

-->
    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css"%}">

    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.css"%}">

    <link rel="stylesheet" href="{% static "css/templatemo-training-studio.css"%}">

    </head>

    <body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
      <div class="preloader-inner">
        <span class="dot"></span>
        <div class="dots">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </div>
    <!-- ***** Preloader End ***** -->


    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">Covid<em> -19</em></a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="#features">Sebaran Covid-19</a></li>
                            <li class="scroll-to-section"><a href="{% url 'projectapp:daftarrsrujukan'%}">Daftar RS Rujukan</a></li>
                            <li class="scroll-to-section"><a href="#trainers">Berita</a></li>
                            <form class="form-inline d-flex justify-content-center md-form form-sm active-pink-2 mt-2">
                              <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
                            </form>
                            <li class="main-button"><a href="{% url 'projectapp:coba'%}">Coba</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    <div class="main-banner" id="top">
        <video autoplay muted loop id="bg-video">
            <source src="{% static "images/caracegahpenularanviruscorona.mp4" %}" type="video/mp4" />
        </video>

        <div class="video-overlay header-text">
            <div class="caption">
                <h2>tanya tentang gejala <em>covid-19</em></h2>
                <div class="main-button scroll-to-section">
                    <a href="{% url 'projectapp:gejala' %}">tanya disini</a>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->

<!-- Data global dan dunia -->
<!-- ***** Features Item Start ***** -->
<div class="center-div">
    <section class="section" id="features">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Data Sebaran <em>Covid-19</em></h2>
                        <img src="{% static "images/line-dec.png" %}" alt="waves">
                        <p></p>
                        <a href="https://covid19.who.int/">Lihat Sebaran Covid-19 di Dunia disini</a>
                        <p></p>
                        <a href="https://covid19.go.id/peta-sebaran">Lihat Sebaran Covid-19 di Indonesia disini</a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <ul class="features-items">
                        <li class="feature-item">
                            <div class="left-icon">
                                <h1><b>3 442 234</b></h1>
                            </div>
                            <div class="right-content">
                                <h4>Terkonfirmasi (Dunia)</h4>
                                <p>Sumber WHO, Update Terakhir: 5 Mei 2020</p>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <h1><b>1 160 000</b></h1>
                            </div>
                            <div class="right-content">
                                <h4>Sembuh (Dunia)</h4>
                                <p>Sumber Google, Update Terakhir: 5 Mei 2020</p>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <h1><b>239 740</b></h1>
                            </div>
                            <div class="right-content">
                                <h4>Meninggal (Dunia)</h4>
                                <p>Sumber WHO, Update Terakhir: 5 Mei 2020</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul class="features-items">
                        <li class="feature-item">
                            <div class="left-icon">
                                <h1><b>11 587</b></h1>
                            </div>
                            <div class="right-content">
                                <h4>Terkonfirmasi (Indonesia)</h4>
                                <p>Sumber covid19.go.id, Update Terakhir: 5 Mei 2020</p>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <h1><b>1 954</b></h1>
                            </div>
                            <div class="right-content">
                                <h4>Sembuh (Indonesia)</h4>
                                <p>Sumber covid19.go.id, Update Terakhir: 5 Mei 2020</p>
                            </div>
                        </li>
                        <li class="feature-item">
                            <div class="left-icon">
                                <h1><b>864</b></h1>
                            </div>
                            <div class="right-content">
                                <h4>Meninggal (Indonesia)</h4>
                                <p>Sumber cobid19.go.id, Update Terakhir: 5 Mei 2020</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
  </div>
    <!-- ***** Features Item End ***** -->

<hr style="height:4px;border:none;color:#000033;background-color:#000033;" />

    <!-- ***** Testimonials Starts ***** -->
    <section class="section" id="trainers">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2><em>Berita</em> Covid-19 Terkini</h2>
                        <img src="{% static "images/line-dec.png" %}" alt="">
                        <p></p>
                        <a href="https://covid19.go.id/p/berita">Lihat Berita Lainnya Disini</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="trainer-item">
                        <div class="image-thumb">
                            <img src="https://covid19.go.id/storage/app/uploads/public/5eb/0c1/230/5eb0c1230a196084393409.jpeg" alt="">
                        </div>
                        <div class="down-content">
                            <span>05 Mei 2020</span>
                            <p><h4>Presiden Jokowi Ajak Negara Gerakan Non-Blok Tingkatkan Solidaritas Politik dalam Melawan Covid-19</h4></p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="trainer-item">
                        <div class="image-thumb">
                            <img src="https://covid19.go.id/storage/app/uploads/public/5ea/fdd/1f0/5eafdd1f02b94061876728.jpeg" alt="">
                        </div>
                        <div class="down-content">
                            <span>04 Mei 2020</span>
                            <p><h4>Pasien Sembuh COVID-19 Menjadi 1.954, Sebanyak 18 Provinsi Tak Laporkan Kasus Baru</h4></p>
                            <br>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="trainer-item">
                        <div class="image-thumb">
                            <img src="https://covid19.go.id/storage/app/uploads/public/5ea/fda/8e2/5eafda8e29055216826912.jpg" alt="">
                        </div>
                        <div class="down-content">
                            <span>04 Mei 2020</span>
                            <p><h4>Infografis COVID-19 (4 Mei 2020)</h4></p>
                            <br><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Testimonials Ends ***** -->


    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2020 Training Studio

                    - Designed by <a rel="nofollow" href="https://templatemo.com" class="tm-text-link" target="_parent">TemplateMo</a></p>

                    <!-- You shall support us a little via PayPal to info@templatemo.com -->

                </div>
            </div>
        </div>
    </footer>



    <!-- jQuery -->
    <script src="{% static "js/jquery-2.1.0.min.js" %}"></script>

    <!-- Bootstrap -->
    <script src="{% static "js/popper.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Plugins -->
    <script src="{% static "js/scrollreveal.min.js" %}"></script>
    <script src="{% static "js/waypoints.min.js" %}"></script>
    <script src="{% static "js/jquery.counterup.min.js" %}"></script>
    <script src="{% static "js/imgfix.min.js" %}"></script>
    <script src="{% static "js/mixitup.js" %}"></script>
    <script src="{% static "js/accordions.js" %}"></script>

    <!-- Global Init -->
    <script src="{% static "js/custom.js" %}"></script>

  </body>
</html>